name: build
on:
  push:
    branches: [ develop ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - run: npm install
      - run: npm run build
      - run: git checkout -- package-lock.json
      - run: npm run lint

        if: success()  # Выполняется только если все предыдущие шаги были успешны
      - name: Set Git config
        run: |
          git config --global user.name 'pointjkee'
          git config --global user.email 'razoranet@gmail.com'
      - name: Merge develop to master
        run: |
          git fetch --unshallow
          git checkout master
          git pull
          git merge --no-ff develop -m 'Auto-merge to master'
          git push